services:
  db:
    build: ./db
    image: phishing_db
    container_name: phishing_db
    ports:
      - 3306:3306
    networks:
      - app_network
  server:
    build: ./server
    image: phishing_server
    container_name: phishing_server
    ports:
      - 8080:8080
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app_network
  client:
    build: ./client
    image: phishing_client
    container_name: phishing_client
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
