CREATE DATABASE IF NOT EXISTS phishing;

USE phishing;

CREATE TABLE IF NOT EXISTS registers(
  id INT AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);